### ISSUE TITLE
Please provide RSA-PSK patch based on OpenSSL 1.0.2 stable release from 22.01.2015

### ISSUE THREAD

**Issue by psytester** [BeID-lab/eIDClientCore#22]
Since the RSA-PSK patch does not work on the final OpenSSL 1.0.2 stable release from 22.01.2015, please provide an update for that.
http://openssl.org/source/openssl-1.0.2.tar.gz

**Comment by psytester** [comment]
Patching on given openssl-1.0.2.tar.gz will be static, as the tarball will not be replaced by a bug or security fix.
If there is an update a new tarball with letter is released, e.g. openssl-1.0.2a.tar.gz
As we would still stay at openssl-1.0.2.tar.gz it should be no problem.
 
https://www.openssl.org/support/faq.html#MISC8
"
After the release of OpenSSL 1.0.0 the versioning scheme changed. Letter releases (e.g. 1.0.1a) can only contain bug and security fixes and no new features. Minor releases change the last number (e.g. 1.0.2) and can contain new features that retain binary compatibility. Changes to the middle number are considered major releases and neither source nor binary compatibility is guaranteed.
"

**Comment by wolfmueller** [comment]
Openssl Patch updated in version ecef44f39cc6d31544b2e1063a4d4a72a772bf2d.
