### ISSUE TITLE
Graceful close eID dialog in case of failure / timeout in PAOS StartConnection

### ISSUE THREAD

**Issue by psytester** [BeID-lab/eIDClientCore#26]
In case the PAOS connection gets back a failure in PAOS Response the eID Client does not stop the eID Dialog.
Failure Response is indicated by:
\<ResultMajor\>http.bsi.bund.de/ecard/api/1.1/resultmajor#error\</ResultMajor\>
(ResultMinor might be = "dp#timeout", but the minor reason is not for interest here.)

In eIDClientCore.cpp at line 1135 – 1137 the fetching of details fails for getCertificateInformation(), getCertificateValidDates() and getChatInformation(), but the whole communication is not stopped.
Some chip communication is done, the next error is detected with “getCHR failed”, the CAR is read and finally we get a segmentation fault.

Required is that the received PAOS message has to be checked against ResultMajor = resultmajor#error and then closes the connections and stop further steps for that eID dialog.

Maybe an additional fail safe check is to evaluate the result Booleans of getCertificateInformation(), getCertificateValidDates() and getChatInformation() and if one of them is false a eIDClientConnectionEnd is done as well.

**Comment by psytester** [comment]
Due to the final segmentation fault in that error case, I'm not able to run a stable load Generator.
Please fix that issue as first point.

**Comment by psytester** [comment]
I catch this issue latly, because for statistic reasons (output of successful read count and server errors), I need to go to the end of the while loop in Test_nPAClientLib.cpp and removed all "continue" statements.
With "continue" statements I do not get a segmentation fault anymore, but the statistic is not longer given in case of error.

1. Please check result Booleans of getCertificateInformation(), getCertificateValidDates() and getChatInformation() and do a "return error;" in eIDClientCore.cpp function nPAeIdPerformAuthenticationProtocolWithParamMap()

2. provide the Output of statistic output in Test_nPAClientLib.cpp as function. This can be called before each "continue" Statement or finally at the end of each loop run.

**Comment by eriknellessen** [comment]
Fixed in ac4793f1f4e2cc657371c09ab1d803e5de0abc06.
