### ISSUE TITLE
Option -p to provide PIN does not work anymore, I'm asked for a PIN

### ISSUE THREAD

**Issue by psytester** [BeID-lab/eIDClientCore#48]
The automation mode does not longer work.
I provide via Option -p <my PIN> but I'm asked each time to enter it.
Comparing to March the eidui_cli.cpp contains now a check if pin is required and requests a PIN.

Please provide a fix that my provided pin is used again.

**Comment by wolfmueller** [comment]
Please describe your observations a bit more in detail. 
- Where the -p Option is parsed? (full path)
- Which revisions did you compare (hash, hash)

**Comment by eriknellessen** [comment]
Fixed in 9c21f723d08f847f01631b36f665b99dccfa9d93. Please test.

**Comment by psytester** [comment]
Yes that's it, it works again :-)
But your change needs my current pull request #47 as well !!!
