### ISSUE TITLE
Missing documentation for Android App

### ISSUE THREAD

**Issue by frankmorgner** [BeID-lab/eIDClientCore#55]

**Comment by eriknellessen** [comment]
The documentation can be found at [this folder](https://github.com/BeID-lab/eIDClientCore/tree/master/eIDClientCore/android/eIDCCAusweisApp2/#welcome).

I added a link to the documentation in README.md in f57c532501e6c9ae09ef6a465a59644e689f4e84.

**Comment by frankmorgner** [comment]
Thanks! For what do you have the TODO section?
