### ISSUE TITLE
getopt is not available on Windows

### ISSUE THREAD

**Issue by frankmorgner** [BeID-lab/eIDClientCore#75]

**Comment by eriknellessen** [comment]
How is this not solved with 85517432f03c947325fd4e9de7a544633a1b0cb7?

**Comment by frankmorgner** [comment]
I wasn't aware that we already included this submodule. So the only thing that's left is include wingetopt in https://github.com/BeID-lab/eIDClientCore/blob/master/eIDClientCore/bin/Test_nPAClientLib/Makefile.am
